[workspace]

members = ["vmmap", "dumper", "scanner", "ffi", "ptrsx", "linux-pc"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
overflow-checks = false
panic = "abort"
strip = true
debug = false
